var buttons =
{
    list:
	{
        "confirm":
		{
            name:"confirm",
            frames:1,
            visible:0
        },
        "start":
		{
            name:"start",
            frames:1,
            visible:0
        },
        "first_survey":
		{
            name:"first_survey",
            frames:1,
            visible:0
        },
        "return_survey":
		{
            name:"return_survey",
            frames:1,
            visible:0
        },
        "last_survey":
		{
            name:"last_survey",
            frames:1,
            visible:0
        },
        "first_survey_qr":
		{
            name:"first_survey_qr",
            frames:1,
            visible:0
        },
        "return_survey_qr":
		{
            name:"return_survey_qr",
            frames:1,
            visible:0
        },
        "last_survey_qr":
		{
            name:"last_survey_qr",
            frames:1,
            visible:0
        },
        "rent":
        {
            name:"rent",
            frames:2,
            visible:0,
            cost:40
        },
        "aircon_heating":
        {
            name:"aircon_heating",
            frames:2,
            visible:0,
            cost:10
        },
        "food":
        {
            name:"food",
            frames:2,
            visible:0,
            cost:5
        },
        "social":
        {
            name:"social",
            frames:2,
            visible:0,
            cost:15
        },
        "family":
        {
            name:"family",
            frames:2,
            visible:0,
            cost:20
        }
    }
}