var flags =
{
    CELL_COLLISION_MODE_OFF:0,
    CELL_COLLISION_MODE_SOFT:1,
    CELL_COLLISION_MODE_WEAK:10,
    CELL_COLLISION_MODE_MEDIUM:100,
    CELL_COLLISION_MODE_HARD:1000,
    CELL_COLLISION_MODE_FULL:10000,

    CELL_COLLISION_MODE_SOFT_LIMIT:1,
    CELL_COLLISION_MODE_MEDIUM_LIMIT:100,

    LAYER_UNLOCKED:0,
    LAYER_SUBMERGE_LOCKED:1,
    LAYER_SURFACE_LOCKED:2,
    LAYER_AIR_LOCKED:3,

    FOG_X:0,
    FOG_O:1,
    FOG_NW:2,
    FOG_NE:3,
    FOG_SW:4,    
    FOG_SE:5,
    FOG_N:6,
	FOG_W:7,
    FOG_E:8,
    FOG_S:9,

    PAN_NONE:0,
    PAN_LEFT:1,
    PAN_RIGHT:2,
    PAN_UP:3,
    PAN_DOWN:4,

    GAME_OVER:false,

    CEF_ACCESS:false,
}