var materials =
{
    list:
	{
        "slides1":
		{
            index:0,
            frames:5
        },
        "story1":
		{
            index:0
        },
        "notes1":
        {
            index:0,
            frames:1
        },
        "textbook1":
        {
            index:0,
            frames:1
        },
        "slides2":
		{
            index:0,
            frames:12
        },
        "story2":
		{
            index:0
        },
        "notes2":
        {
            index:0,
            frames:1
        },
        "textbook2":
        {
            index:0,
            frames:1
        },
        "slides3":
		{
            index:0,
            frames:8
        },
        "story3":
		{
            index:0
        },
        "notes3":
        {
            index:0,
            frames:1
        },
        "textbook3":
        {
            index:0,
            frames:1
        },
        "slides4":
		{
            index:0,
            frames:10
        },
        "story4":
		{
            index:0
        },
        "notes4":
        {
            index:0,
            frames:1
        },
        "textbook4":
        {
            index:0,
            frames:1
        },
        "slides5":
		{
            index:0,
            frames:11
        },
        "story5":
		{
            index:0
        },
        "notes5":
        {
            index:0,
            frames:1
        },
        "textbook5":
        {
            index:0,
            frames:1
        },
        "slides6":
		{
            index:0,
            frames:13
        },
        "story6":
		{
            index:0
        },
        "notes6":
        {
            index:0,
            frames:1
        },
        "textbook6":
        {
            index:0,
            frames:1
        },

        "slides7":
		{
            index:0,
            frames:12
        },
        "story7":
		{
            index:0
        },
        "notes7":
        {
            index:0,
            frames:1
        },
        "textbook7":
        {
            index:0,
            frames:1
        },
        "slides8":
		{
            index:0,
            frames:12
        },
        "story8":
		{
            index:0
        },
        "notes8":
        {
            index:0,
            frames:1
        },
        "textbook8":
        {
            index:0,
            frames:1
        },
        "slides9":
		{
            index:0,
            frames:12
        },
        "story9":
		{
            index:0
        },
        "notes9":
        {
            index:0,
            frames:1
        },
        "textbook9":
        {
            index:0,
            frames:1
        },
        "slides10":
		{
            index:0,
            frames:11
        },
        "story10":
		{
            index:0
        },
        "notes10":
        {
            index:0,
            frames:1
        },
        "textbook10":
        {
            index:0,
            frames:1
        },
        "slides11":
		{
            index:0,
            frames:13
        },
        "story11":
		{
            index:0
        },
        "notes11":
        {
            index:0,
            frames:1
        },
        "textbook11":
        {
            index:0,
            frames:1
        },
        "slides12":
		{
            index:0,
            frames:14
        },
        "story12":
		{
            index:0
        },
        "notes12":
        {
            index:0,
            frames:1
        },
        "textbook12":
        {
            index:0,
            frames:1
        },
    },
}